swagger: '2.0'
info:
  title: API_ID optional-string
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /todo:
    get:
      summary: TodoAPI server
      operationId: TODO Apis
      x-google-backend:
        address: $ALLOWED_AUDIENCE_URL/todo
      security:
      - google_id_token: []    
      responses:
        '200':
          description: A successful response
          schema:
            type: string
securityDefinitions:
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
    x-google-audiences: "https://$GATEWAY_HOSTNAME"  